---
- hosts: webservers
  tasks:
      - name: Update packages
        become: true
        apt:
          update_cache: yes

      - name: Download nginx
        become: true
        apt: name=nginx state=present
     
      - name: Run nginx
        become: true
        service:
          name: nginx
          state: started
